"""Add CPU, RAM, Storage

Revision ID: 5f3d23060031
Revises: 
Create Date: 2026-01-05 16:50:36.434346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '5f3d23060031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('HardDiskHistorical', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.drop_index(batch_op.f('IX_HardDiskBackup_Modified'))
        batch_op.drop_index(batch_op.f('IX_HardDiskBackup_Serial'))
        batch_op.create_index(batch_op.f('ix_HardDiskHistorical_serial_number'), ['serial_number'], unique=False)

    with op.batch_alter_table('ServerAssets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpu', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('storage', sa.String(length=50), nullable=True))
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mssql.DATETIME2(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('(sysdatetime())'))
        batch_op.drop_index(batch_op.f('IX_ServerAssets_Hostname'))
        batch_op.drop_index(batch_op.f('IX_ServerAssets_IP'))
        batch_op.drop_index(batch_op.f('IX_ServerAssets_Segment'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True)

    with op.batch_alter_table('ServerAssets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('IX_ServerAssets_Segment'), ['segment'], unique=False)
        batch_op.create_index(batch_op.f('IX_ServerAssets_IP'), ['ip_address'], unique=False)
        batch_op.create_index(batch_op.f('IX_ServerAssets_Hostname'), ['hostname'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIME2(),
               nullable=False,
               existing_server_default=sa.text('(sysdatetime())'))
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)
        batch_op.drop_column('storage')
        batch_op.drop_column('ram')
        batch_op.drop_column('cpu')

    with op.batch_alter_table('HardDiskHistorical', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_HardDiskHistorical_serial_number'))
        batch_op.create_index(batch_op.f('IX_HardDiskBackup_Serial'), ['serial_number'], unique=False)
        batch_op.create_index(batch_op.f('IX_HardDiskBackup_Modified'), ['modified'], unique=False)
        batch_op.alter_column('serial_number',
               existing_type=sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False)

    # ### end Alembic commands ###
